// Commons inserter against the REAL Commons API; admin/page endpoints are mocked.
import { chromium } from 'playwright'
import { parse } from 'yaml'
const base = process.argv[2]
let fails = 0
const ok = (n, c, x = '') => { console.log(c ? 'ok  ' : 'FAIL', n, c ? '' : x); if (!c) fails++ }
const b = await chromium.launch({ channel: 'chrome' })
const p = await b.newPage({ viewport: { width: 1280, height: 900 } })
const errs = []; p.on('pageerror', (e) => errs.push(e.message.slice(0, 200)))
const puts = []
await p.route('**/api/auth/me', (r) => r.fulfill({ json: { user: { id: '5554', username: 'Yug' }, admin: true } }))
await p.route('**/api/admin/page**', (r) => { const q = r.request(); if (q.method() === 'PUT') { puts.push(q.postDataJSON()); return r.fulfill({ json: { ok: true } }) } return r.fulfill({ json: { path: '/x', text: '---\ntitle: "X"\ntype: "post"\nstatus: "publish"\ndate: "2026-01-01T10:00:00"\n---\n\nAntes.\n' } }) })
await p.goto(`${base}/admin/edit/?path=/x`, { waitUntil: 'load' })
await p.waitForSelector('.cm-content', { timeout: 15000 })
await p.locator('.cm-content').click(); await p.keyboard.press('Control+End')
await p.click('button:has-text("🖼 Commons")')
ok('dialog opens', await p.locator('dialog.cfi').evaluate((d) => d.open))
ok('search disabled while empty', await p.locator('.search button').isDisabled())
await p.fill('#cfi-q', 'Machu Picchu'); await p.keyboard.press('Enter')
await p.waitForSelector('.grid li', { timeout: 20000 })
await p.waitForFunction(() => !document.body.innerText.includes('Cargando…'), null, { timeout: 20000 })
const n = await p.locator('.grid li').count()
ok(`search returns thumbnails (${n})`, n >= 10)
ok('thumbnails come from Commons', (await p.locator('.grid img').first().getAttribute('src')).match(/^https:\/\/(upload|thumb)\.wikimedia\.org\//))
await p.locator('.grid li button').first().click()
await p.waitForSelector('.detail .prev', { timeout: 20000 })
const md = await p.locator('.md').innerText()
console.log('--- generated markdown:\n' + md + '\n---')
ok('markdown image from upload.wikimedia.org', /^!\[[^\]]+\]\(https:\/\/(upload|thumb)\.wikimedia\.org\/[^ )]+/.test(md))
ok('credit line has license + Commons link', /vía Wikimedia Commons\]\(https:\/\/commons\.wikimedia\.org\/wiki\/File:/.test(md))
ok('alt text prefilled', (await p.locator('.detail input[required]').inputValue()).length > 3)
await p.fill('.detail input[required]', ''); ok('insert blocked without alt text', await p.locator('.ins').isDisabled())
await p.fill('.detail input[required]', 'Vista de la ciudadela [inca] "Machu Picchu"')
await p.uncheck('.chk input'); const md2 = await p.locator('.md').innerText()
ok('alt text sanitised (no brackets/quotes), credit removable', !md2.includes('\n') && md2.startsWith('![Vista de la ciudadela inca \'Machu Picchu\'](') , md2.slice(0, 120))
await p.check('.chk input')
await p.click('.ins')
ok('dialog closed after insert', !(await p.locator('dialog.cfi').evaluate((d) => d.open)))
const editor = await p.locator('.cm-content').innerText()
ok('inserted at the cursor, after the existing text', editor.indexOf('Antes.') < editor.indexOf('!['), editor.slice(0, 160))
await p.click('.save'); await p.waitForTimeout(800)
ok('saved text contains the image', /(upload|thumb)\.wikimedia\.org/.test(puts[0]?.text ?? ''))
ok('frontmatter still valid', parse(puts[0].text.match(/^---\n([\s\S]*?)\n---/)[1]).title === 'X')
// More results + no-result query
await p.click('button:has-text("🖼 Commons")'); await p.fill('#cfi-q', 'qzxwvv nonsense query 7788'); await p.keyboard.press('Enter'); await p.waitForTimeout(3000)
ok('nonsense query shows "Sin resultados"', (await p.locator('text=Sin resultados').count()) === 1)
await p.keyboard.press('Escape'); ok('Esc closes the dialog', !(await p.locator('dialog.cfi').evaluate((d) => d.open)))
ok('no page errors', errs.length === 0, errs.join('|'))
await b.close()
console.log(fails ? `\n${fails} FAILED` : '\nALL PASSED'); process.exit(fails ? 1 : 0)
