#!/usr/bin/env python3
"""Compute the MINIMAL sample of content/data/media that is committed to git, and write it down.

The sample is what a visitor sees on the main pages: the pages reachable from the menu and footer, the home page and
what it embeds (latest news, partners carousel, press notes), and page 1 of every listing (news, resources, partners).
Everything else is rebuilt from WordPress after `git clone` (`tools/wp/wp bootstrap`).

  sample.py            recompute from the CURRENT full site and rewrite: tools/wp/sample.json, the generated block of
                       .gitignore, tools/wp/seed-data/*.json (pruned copies of the generated data)
  sample.py --media    also recompress the sample media in place (max 800 px, JPEG q75) to keep the repo light
Run it on a machine that has the full site (before a push that should change the sample).
"""
import json, math, re, sys
from pathlib import Path
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from wpimport import indexes  # noqa: E402

PER_PAGE = 9
BEGIN, END = "# >>> sample whitelist (generated by tools/wp/sample.py — do not edit by hand) >>>", "# <<< sample whitelist <<<"
CURATED_DATA = ["data/menu.json", "data/medios.json", "data/partners-featured.json", "data/redirects.json"]
GENERATED_DATA = ["routes", "taxonomies", "taxonomy-index", "media-index"]


def jload(p, d=None):
    try: return json.loads(Path(p).read_text())
    except (OSError, ValueError): return d


def compute():
    pages = {r: (f, fm) for r, f, fm in indexes.local_pages(ROOT / "content")}
    menu, keep = jload(ROOT / "data/menu.json", []), {}
    def add(route, why):
        route = "/" + route.strip("/") if route.strip("/") else "/"
        if route in pages: keep.setdefault(route, why)
    def flat(items):
        for i in items:
            yield i["url"]; yield from flat(i.get("children", []))
    for u in flat(menu): add(u, "menu")
    for r, why in [("/", "home"), ("/wikiaccion-peru-en-medios", "press page"), ("/comunidad-en-expansion", "community page"), ("/recurso/manual-de-edicion-en-wikipedia", "footer link")]: add(r, why)
    newest = lambda t, n: [r for _, r in sorted(((fm.get("date", ""), r) for r, (f, fm) in pages.items() if fm.get("type") == t and fm.get("status", "publish") == "publish"), reverse=True)[:n]]
    for r in newest("post", PER_PAGE): add(r, "news page 1, home band, recent posts")
    for r in newest("recurso", PER_PAGE): add(r, "resources page 1")
    for r in newest("alianza", PER_PAGE): add(r, "partners page 1")
    for s in jload(ROOT / "data/partners-featured.json", []): add("/alianza/" + s, "home partners carousel")
    mi = jload(ROOT / "data/media-index.json", {})
    media = set()
    texts = [pages[r][0].read_text() for r in keep] + [(ROOT / p).read_text() for p in CURATED_DATA if (ROOT / p).exists()]
    for f in [*Path(ROOT / "app").rglob("*"), ROOT / "nuxt.config.ts"]:
        if f.is_file() and f.suffix in (".vue", ".ts"): texts.append(f.read_text())
    for t in texts:
        media |= {unquote(m) for m in re.findall(r"/media/([\w./%~-]+\.(?:png|jpe?g|webp|svg|gif))", t)}
    for r in keep:
        fid = pages[r][1].get("featured_media")
        if fid and str(fid) in mi: media.add(mi[str(fid)][len("/media/"):])
    return pages, keep, sorted(m for m in media if (ROOT / "public/media" / m).exists()), mi


def main():
    pages, keep, media, mi = compute()
    content = sorted(str(pages[r][0].relative_to(ROOT)) for r in keep)
    # pruned generated data (the fallback a fresh clone starts from)
    tax = jload(ROOT / "data/taxonomies.json", {})
    idx = jload(ROOT / "data/taxonomy-index.json", {})
    used = {(t, s) for r in keep for t, ss in (pages[r][1].get("taxonomies") or {}).items() for s in ss}
    tax_seed = {t: {**d, "terms": [x for x in d["terms"] if len(d["terms"]) <= 12 or (t, x["slug"]) in used]} for t, d in tax.items()}
    idx_seed = {k: [r for r in v if r in keep] for k, v in idx.items() if any(r in keep for r in v)}
    mi_seed = {k: v for k, v in mi.items() if v[len("/media/"):] in set(media)}
    routes = set(); n = lambda c: max(0, math.ceil(c / PER_PAGE))
    routes |= {"/", "/styleguide", "/buscar", "/admin", "/admin/pages", "/admin/menu", "/admin/editors", "/admin/edit", "/noticias", "/recursos", "/alianza", "/search-index.json"} | set(keep)
    for k, v in idx_seed.items():
        t, s = k.split("/", 1); pre = tax_seed.get(t, {}).get("prefix")
        if pre: routes.add(f"/{pre}/{s}")
    seed = ROOT / "tools/wp/seed-data"; seed.mkdir(parents=True, exist_ok=True)
    for name, val in {"routes": sorted(routes), "taxonomies": tax_seed, "taxonomy-index": idx_seed, "media-index": mi_seed}.items():
        (seed / f"{name}.json").write_text(json.dumps(val, ensure_ascii=False, indent=None if name != "routes" else 1))
    manifest = {"content": content, "media": [f"public/media/{m}" for m in media], "data": CURATED_DATA, "seed-data": [f"tools/wp/seed-data/{n}.json" for n in GENERATED_DATA]}
    (ROOT / "tools/wp/sample.json").write_text(json.dumps(manifest, indent=1, ensure_ascii=False))
    # .gitignore block: ignore files (not directories, so `!` can re-include), then whitelist
    lines = [BEGIN, "/content/**/*.md", "/public/media/**/*.*", "/data/*.json", "/import/state.json", "/var/", *[f"!/{p}" for p in content + manifest["media"] + CURATED_DATA], END]
    gi = (ROOT / ".gitignore").read_text()
    gi = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", gi, flags=re.S).rstrip("\n") + "\n\n" + "\n".join(lines) + "\n"
    (ROOT / ".gitignore").write_text(gi)
    size = sum((ROOT / p).stat().st_size for p in manifest["media"] if (ROOT / p).exists())
    print(f"sample: {len(content)} pages, {len(manifest['media'])} media files ({size / 1e6:.1f} MB), {len(CURATED_DATA)} curated + {len(GENERATED_DATA)} seed data files")
    if "--media" in sys.argv:
        from PIL import Image
        saved = 0
        for p in manifest["media"]:
            f = ROOT / p
            if f.suffix.lower() not in (".jpg", ".jpeg", ".png", ".webp"): continue
            before = f.stat().st_size
            with Image.open(f) as im:
                if getattr(im, "is_animated", False): continue
                fmt = im.format; im.load()
                im2 = im.copy(); im2.thumbnail((800, 800), Image.LANCZOS)
            tmp = f.with_name(f.name + ".tmp")
            kw = {"quality": 75, "optimize": True, "progressive": True} if fmt == "JPEG" else {"optimize": True}
            if fmt == "JPEG" and im2.mode not in ("RGB", "L"): im2 = im2.convert("RGB")
            im2.save(tmp, format=fmt, **kw)
            if tmp.stat().st_size < before: tmp.replace(f); saved += before - f.stat().st_size  # replace breaks any hardlink to extract/
            else: tmp.unlink()
        size = sum((ROOT / p).stat().st_size for p in manifest["media"] if (ROOT / p).exists())
        print(f"recompressed: saved {saved / 1e6:.1f} MB -> sample media now {size / 1e6:.1f} MB")


if __name__ == "__main__":
    main()
